server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: springboot-init-security
  # 默认 dev 环境
  profiles:
    active: dev

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_dbs
    username: root
    password: root
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456

mybatis:
  type-aliases-package: com.murphy.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true   ##开启驼峰


####自定义 ConfigConstant zh_CN en_US ####
config:
  #filePath: classpath:/static/file
  filePath: D:\Environment\nginx-1.24.0\static\file